---

- name: Ensure caddy paths exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ caddy_uid }}"
    group: "{{ caddy_gid }}"
  with_items:
    - "{{ caddy_base_path }}"
    - "{{ caddy_config_path }}"
    - "{{ caddy_data_path }}"

- name: Ensure caddy configuration files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}"
    dest: "{{ caddy_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ caddy_uid }}"
    group: "{{ caddy_gid }}"
  with_items:
    - Caddyfile

- name: Ensure caddy image is pulled
  community.docker.docker_image:
    name: "{{ caddy_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ caddy_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else caddy_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure caddy container network is created
  community.general.docker_network:
    name: "{{ caddy_container_network }}"
    driver: bridge

- name: Ensure caddy systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/caddy.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ caddy_identifier }}.service"
    mode: "0644"
