---

- name: Check existence of Caddy systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ caddy_identifier }}.service"
  register: caddy_service_stat

- when: caddy_service_stat.stat.exists | bool
  block:
    - name: Ensure Caddy is stopped
      ansible.builtin.service:
        name: "{{ caddy_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Caddy systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ caddy_identifier }}.service"
        state: absent

    - name: Ensure Caddy base path doesn't exist
      ansible.builtin.file:
        path: "{{ caddy_base_path }}"
        state: absent
